### ISSUE TITLE
Directories does not realtime sync (drupal8-php-fpm-apache)

### ISSUE THREAD

**Issue by Cobra0107** [srijanone/vega#124]
Steps I took

1. Created project with `drupal8-php-fpm-apache` starterkit.
2. Updated composer.json with EZContent requirement.
3. Run composer install
4. Vega up
5. Install a module with composer
6. Go to php container
7. list the contrib modules
8. The above module does not appear. 

Question: Am I missing something? Or This could be possible bug

**Comment by riteshgurung** [comment]
@WSMathias @AshishThakur Do we have to follow the steps of using command

*   docker-compose run --rm cli composer install
*   vega up

cc @Cobra0107

**Comment by WSMathias** [comment]
@Cobra0107 @riteshgurung 

Steps to  start any drupal project using vega:
---
- `vega init` (Get latest starterkits)
- `vega starterkit list` (get the list of available starterkits)
-  `vega create --starterkit <starterkit name>  <project name>` (new directory with a project name will be created and starter kit will be copied here)
- Update .env file (`PROJECT_NAME`, `APPLICATION_PORT`, `PHP_VERSION`, ....)
- `docker-compose run --rm cli` (It will Install packages defined in the composer.json required to start drupal)
- `vega up' (start application, a browser window will open for application logs)
- `vega down` (stop application)
---
Clean up (To recover some disk space):
---
- `docker-compose down --volumes`  (Clean up MySQL database and  files created by drupal)
- `docker image rm -f $(docker image ls -q --filter "label=builtby=tilt")` (clean up temporary images created by vega)
---
PS: Some of these docker-compose commands will be part of vega in future releases. Refer README present within project provided by starter kit for updated commands

**Comment by sharmaamitt16** [comment]
@Cobra0107 I tried your scenario, it's working fine. You just need to wait till the time your new module gets copied to the container. This modification was done for performance on the non-linux platform. You can check the logs using web UI about container status.

**Comment by Cobra0107** [comment]
Hi @sharmaamitt16 , @riteshgurung, @WSMathias ,

Apologies for late reply, 

Yes indeed had word with @amitsharma334  works as expected seems I was missing few steps. 

Closing this issue since not an issue
