### ISSUE TITLE
Starterkit operations

### ISSUE THREAD

**Issue by AshishThakur** [srijanone/vega#23]
* Provide ability to list installed repos.
* Add a repo
* ~Delete a repo~
* ~Sync(In case the upstream repo is changed, provide an ability to sync).~

**Comment by vs4vijay** [comment]
**Updated API Specs**:

1. `vega repo add <name> <url>` will add given url's starterkits to $VEGA_HOME.
     - It supports local file path as well
     - add operation will only get successful when the given URL/Path has `starterkits/` folder i.e. it should be a valid vega repository.

2. `vega repo list` will list all the repositories added to local machine

3. `vega create --starterkit <name> --repo vs4vijay` will take an optional flag for `repo`. 
    - If `repo` flag is not provided, then `default` is considered.
