### ISSUE TITLE
cli container dies after it tries to delete the drupal config file

### ISSUE THREAD

**Issue by ravindrasingh22** [srijanone/vega#64]
cli container dies after scaffold files for Drupal. follow error kills the cli container - 

`Could not delete /app/web/sites/default/default.services.yml:`

`cli_1     | Deprecation Notice: Class EasyRdf_Parser_JsonLd located in ./vendor/easyrdf/easyrdf/lib/EasyRdf/Parser/JsonLdImplementation.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
cli_1     |   * Homepage: https://www.drupal.org/project/drupal
cli_1     |   * Support:
cli_1     |     * docs: https://www.drupal.org/docs/user_guide/en/index.html
cli_1     |     * chat: https://www.drupal.org/node/314178
cli_1     | Scaffolding files for drupal/core:
cli_1     |   - Copy [project-root]/.editorconfig from assets/scaffold/files/editorconfig
cli_1     |   - Copy [project-root]/.gitattributes from assets/scaffold/files/gitattributes
cli_1     |   - Copy [web-root]/.csslintrc from assets/scaffold/files/csslintrc
cli_1     |   - Copy [web-root]/.eslintignore from assets/scaffold/files/eslintignore
cli_1     |   - Copy [web-root]/.eslintrc.json from assets/scaffold/files/eslintrc.json
cli_1     |   - Copy [web-root]/.ht.router.php from assets/scaffold/files/ht.router.php
cli_1     |   - Copy [web-root]/.htaccess from assets/scaffold/files/htaccess
cli_1     |   - Copy [web-root]/example.gitignore from assets/scaffold/files/example.gitignore
cli_1     |   - Copy [web-root]/index.php from assets/scaffold/files/index.php
cli_1     |   - Copy [web-root]/INSTALL.txt from assets/scaffold/files/drupal.INSTALL.txt
cli_1     |   - Copy [web-root]/README.txt from assets/scaffold/files/drupal.README.txt
cli_1     |   - Copy [web-root]/robots.txt from assets/scaffold/files/robots.txt
cli_1     |   - Copy [web-root]/update.php from assets/scaffold/files/update.php
cli_1     |   - Copy [web-root]/web.config from assets/scaffold/files/web.config
cli_1     |   - Copy [web-root]/sites/README.txt from assets/scaffold/files/sites.README.txt
cli_1     |   - Copy [web-root]/sites/development.services.yml from assets/scaffold/files/development.services.yml
cli_1     |   - Copy [web-root]/sites/example.settings.local.php from assets/scaffold/files/example.settings.local.php
cli_1     |   - Copy [web-root]/sites/example.sites.php from assets/scaffold/files/example.sites.php
cli_1     |
cli_1     |
cli_1     |   [RuntimeException]
cli_1     |   Could not delete /app/web/sites/default/default.services.yml:
cli_1     |
cli_1     |
cli_1     | install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...
cli_1     |
crossword_cli_1 exited with code 1`

**Comment by vs4vijay** [comment]
@ravindrasingh22 - What command did you execute? and do you have root permission on your machine?

**Comment by ravindrasingh22** [comment]
I do have permission on my system but my user doesn't have permission. Please tell what has to be executed.

**Comment by ravindrasingh22** [comment]
simple commands 
after setup
vega up
it runs all the container well but cli gets crashed while copying the files 

  - Copy [web-root]/sites/example.settings.local.php from assets/scaffold/files/example.settings.local.php
  - Copy [web-root]/sites/example.sites.php from assets/scaffold/files/example.sites.php

                                                                 
  [RuntimeException]                                             
  Could not delete /app/web/sites/default/default.services.yml:

**Comment by WSMathias** [comment]
@ravindrasingh22 we Have identified the root cause of the issue.
As per the discussion on the drupal forum [here][1] and composer-scaffolding [doc][2] we have added file-mapping to the composer.json
https://github.com/srijanone/vega/blob/981341df6f964a9ff3e47e2619df12e1a969a80e/starterkits/drupal8-php-fpm-apache/composer.json#L39-L42


[1]: https://www.drupal.org/forum/support/post-installation/2019-12-09/fresh-install-drupal-880-composer-require-could-not
[2]: https://www.drupal.org/docs/develop/using-composer/using-drupals-composer-scaffold
