### ISSUE TITLE
As a developer I should be able to view the application/service logs

### ISSUE THREAD

**Issue by AshishThakur** [srijanone/vega#7]
**Description**
* A developer should be able to view the application logs.
* Provide a command line interface to achieve this.
* This is similar to run service in non-daemon mode in docker.
```
vega up # This would stdout the logs
```
NOTE
* The application should stdout the logs else vega won't be able to stream those.
* In the subsequent release vega would provide an graphical interface to view the logs.

**Comment by vs4vijay** [comment]
This is already done with `vega up` command.
