### ISSUE TITLE
Vega Installation Issue - If tried more than once

### ISSUE THREAD

**Issue by shobhitjuyal** [srijanone/vega#71]
If first time installation was not successfull for some reason, the installation script should say "already installed" for further attempts.
However, I still didn't get the working setup even on another attempts.
![vega-installation-issue](https://user-images.githubusercontent.com/25407952/83167682-0d2f6980-a12e-11ea-9a1d-646e1fce030e.png)

**Comment by vs4vijay** [comment]
@shobhitjuyal Which OS you're using? and have you tried running `vega` in separate terminal after this?

**Comment by shobhitjuyal** [comment]
Os is "Ubuntu" v. 18

echo $PATH = 
/home/shobhit/.composer/vendor/bin:/home/shobhit/.composer/vendor/bin:/home/shobhit/.composer/vendor/bin:/home/shobhit/bin:/home/shobhit/.local/bin:/opt/gradle/gradle-5.5/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/opt/netbeans/bin/

which tilt = {no data }

**Comment by vs4vijay** [comment]
I guess tilt got installed to your home directory instead of `/usr/bin/`. Try adding `/home/shobhit/.local/bin` to your path and check,

**Comment by shobhitjuyal** [comment]
The output of 
ls -l /home/shobhit/.local/bin | grep tilt  

is

"drwxr-xr-x 2 shobhit shobhit 4096 May 28 21:51 tilt"

**Comment by WSMathias** [comment]
@shobhitjuyal not enough information to reproduce.
if you can explain what error you got during 1st attempt will be useful.

**Comment by shobhitjuyal** [comment]
I was able to setup Vega manually. Its up and running.

Thanks to @AshishThakur
